// <auto-generated />
using System;
using MedicineAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MedicineAPI.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20221222152018_DbInit")]
    partial class DbInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MedicineAPI.Data.Medicine", b =>
                {
                    b.Property<Guid>("idMedicine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descriptionMedicine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameMedicine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("numberMedicine")
                        .HasColumnType("float");

                    b.HasKey("idMedicine");

                    b.ToTable("Medicine");
                });
#pragma warning restore 612, 618
        }
    }
}
