// <auto-generated />
using System;
using MedicineAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MedicineAPI.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MedicineAPI.Data.Medicine", b =>
                {
                    b.Property<Guid>("idMedicine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descriptionMedicine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("idType")
                        .HasColumnType("int");

                    b.Property<string>("nameMedicine")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("numberMedicine")
                        .HasColumnType("float");

                    b.HasKey("idMedicine");

                    b.HasIndex("idType");

                    b.ToTable("Medicine");
                });

            modelBuilder.Entity("MedicineAPI.Data.Type", b =>
                {
                    b.Property<int>("idType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nameType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idType");

                    b.ToTable("Type");
                });

            modelBuilder.Entity("MedicineAPI.Data.Medicine", b =>
                {
                    b.HasOne("MedicineAPI.Data.Type", "type")
                        .WithMany("Medicines")
                        .HasForeignKey("idType");

                    b.Navigation("type");
                });

            modelBuilder.Entity("MedicineAPI.Data.Type", b =>
                {
                    b.Navigation("Medicines");
                });
#pragma warning restore 612, 618
        }
    }
}
